package modelo;

public enum EstadoJuego {
	ESPERANDO_JUGADORES,
	CAMBIO_LISTA_DE_JUGADORES,
	ERROR_AL_AGREGAR_JUGADOR,
	LISTO_PARA_INICIAR,
	JUGANDO_JUGADOR_1,
	JUGANDO_JUGADOR_2,
	COLUMNA_LLENA,
	ULTIMA_FICHA_JUGADA,
	EMPATE,
	TERMINADO
}
